source 'https://github.com/CocoaPods/Specs.git'

target 'ViperMcFlurry_Example', :exclusive => true do
  pod "ViperMcFlurry", :path => "../"
  pod "Typhoon", '~> 3.2.x'  
end

target 'ViperMcFlurry_Tests', :exclusive => true do
  pod "Typhoon", '~> 3.2.x'
end
