source 'https://github.com/CocoaPods/Specs.git'

target 'RamblerMcFlurry_Example', :exclusive => true do
  pod "RamblerMcFlurry", :path => "../"
end

target 'RamblerMcFlurry_Tests', :exclusive => true do
  pod "RamblerMcFlurry", :path => "../"

  
end
